config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :courses, only: [] do
        member do
          post :like
        end
      end
    end
  end
  
  resources :courses do
    member do
      get :buy
    end
    # resources :reviews, shallow: true
    resources :reviews, only: [:create]
    resources :orders, only: [:create]  #POST /courses/2/orders
  end
  resources :reviews, only: [:destroy]

  root "courses#index"

  get "/about", to: "pages#about"

  # users function
  get "/sign_up", to: "users#sign_up"
  post "/account_verify", to: "users#account_verify"

  get "/sign_in", to: "users#sign_in"
  post "/sign_in/check", to: "users#check"

  delete "/sign_out", to: "users#sign_out"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.random
    self.order(Arel.sql('RANDOM()')).first
  end
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, numericality: {
    greater_than_or_equal_to: 0
  }

  belongs_to :user
  has_many :reviews
  has_many :orders
  
  has_many :fav_courses
  has_many :users, through: :fav_courses

  def prepare_order(params)
    params = params.merge(
      amount: self.price, 
      status: 'pending'
    )
    orders.build(params)
  end
end

app/models/fav_course.rb
class FavCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :course

  after_create :serial_generator

  include AASM

  aasm column: 'status' do #default column: aasm_state
    state :pending, initial: true
    state :paid, :cancelled, :refunded

    event :pay do
      transitions from: :pending, to: :paid

      after do
        update(paid_at: Time.current)
      end
    end

    event :cancel do
      transitions from: [:pending, :paid], to: :cancelled
    end

    event :refund do
      transitions from: [:paid, :cancel], to: :refunded
    end
  end

  private
  def serial_generator
    serial = "NFT#{Time.current.strftime("%Y%m%d")}#{code_generator(7)}"
    update(serial: serial)
  end

  def code_generator(n = 7)
    all_chars = [*'A'..'Z', *'0'..'9']
    confused_chars = ['X', 'S', '0', 'O', 'B', 'P', 'M', 'N', 'D', 'T']

    (all_chars - confused_chars).sample(n).join
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :course, counter_cache: true
end

app/models/user.rb
require "digest"

class User < ApplicationRecord
  validates :email, :username, presence: true

  has_many :courses
  has_many :orders

  has_many :fav_courses
  has_many :favorite_courses, through: :fav_courses, source: :course

  before_create :encrypt_password

  def self.login(user_info)
    email = user_info[:email]
    password = user_info[:password]

    salted_password = "xy#{password.reverse}hellohey"
    encryted_password = Digest::SHA1.hexdigest(salted_password)

    self.find_by(email: email, password: encryted_password)
  end

  private
  def encrypt_password
    salted_password = "xy#{self.password.reverse}hellohey"
    self.password = Digest::SHA1.hexdigest(salted_password)
  end
end

app/controllers/api/v1/courses_controller.rb
class Api::V1::CoursesController < ApplicationController
  # skip_before_action :verify_authenticity_token
  before_action :check_login

  def like
    course = Course.find(params[:id])

    favorited_course = FavCourse.find_by(user: current_user, course: course)
    if favorited_course
      favorited_course.destroy
      render json: { result: 'unlike' }
    else
      current_user.favorite_courses << course
      render json: { result: 'like'}
    end
  end

  private
  def check_login
    if not user_signed_in?
      render json: { status: 'fail', message: 'Nd to log in first'},
      status: 401
      return
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include UsersHelper

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  helper_method :user_signed_in?, :current_user

  private
  def record_not_found
    render file: 'public/404.html', layout: false, status: 404
  end

  def user_signed_in?
    session[:whatever123].present?
  end

  def current_user
    # memorization
    @current_user ||= User.find_by(id: session[:whatever123])
  end

  def authenticate!
    # 如果沒登入，轉去登入頁面
    redirect_to sign_in_path, notice: '請先登入會員' unless user_signed_in?
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:edit, :update, :destroy]
  before_action :authenticate!, except: [:index, :show]

  def index
    @courses = Course.all.includes(:user)
  end

  def show
    @course = Course.find(params[:id])
    @review = Review.new
    @reviews = @course.reviews.order(id: :desc)
  end

  def new
    @course = Course.new
  end

  def buy
    @course = Course.find(params[:id])
    @order = Order.new
    @token = Braintree::TokenGenerator.call
  end
  
  def create
    @course = current_user.courses.build(course_params)

    if @course.save
      redirect_to courses_path, notice: "新增課程成功"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to courses_path, notice: "課程更新成功"
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to courses_path, notice: "課程已刪除"
  end

  private
  def set_course
    @course = current_user.courses.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :price, :intro, :hour)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate!

  def create
    @course = Course.find(params[:course_id])
    @order = @course.prepare_order(order_params)
    # @order.status = 'pending'

    if @order.save
      #swipe card!
      gateway = Braintree::Gateway.new(
        environment: :sandbox,
        merchant_id: ENV['h8jcptc4t6htzcd5'],
        public_key: ENV['556smdxth5jmr7n5'],
        private_key: ENV['22e781fa3cbddd88134c8e561ae49f85']
      )

      result = gateway.transaction.sale(
        amount: @order.amount, 
        payment_method_nonce: params[:nonce]
      )

      if result.success?
        @order.pay! if@order.may_pay?
        redirect_to root_path, notice: 'Successfully Bought!'
      else
        redirect_to root_path, notice: "sth went wrong, please try again later"
      end
    end
  end

  private
  def order_params
    params.require(:order).permit(:recipient, :address).merge(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    render html: params
  end

  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate!

  def create
    course = Course.find(params[:course_id])

    @review = course.reviews.build(review_params)

    if @review.save
      # redirect_to course_path(course), notice: '完成評價'
    else
      # ....
    end
  end

  private
  def review_params
    params.require(:review)
          .permit(:rating, :title, :content)
          .merge(user: current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_up
    @user = User.new
  end

  def account_verify
    @user = User.new(user_params)

    if @user.save
      redirect_to "/"
    else
      render :sign_up
    end
  end

  def sign_in
    @user = User.new
  end

  def check
    u = User.login(params[:user])
    if u
      session[:whatever123] = u.id
      redirect_to "/"
    else
      render html: "no user"
    end
  end

  def sign_out
    session[:whatever123] = nil
    redirect_to courses_path, notice: '已登出'
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/api/v1/courses_helper.rb
module Api::V1::CoursesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # def user_signed_in?
  #   session[:whatever123].present?
  # end

  # def current_user
  #   User.find(session[:whatever123])
  # end
end

app/views/courses/_form.html.erb
<% if course.errors.any? %>
  <ul>
  <% course.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<div data-controller="datepicker">
  <button>Calendar</button>
  <input type="text" id="picker">
</div>

<%= form_with(model: course) do |f| %>
  <div class="fields">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="fields">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div class="fields">
    <%= f.label :intro %>
    <%= f.text_area :intro %>
  </div>
  <div class="fields">
    <%= f.label :hour %>
    <%= f.number_field :hour %>
  </div>

  <%= f.submit btn_label %>
<% end %>

app/views/courses/buy.html.erb
<h1>購買課程</h1>

<%= form_for(@order, url: course_orders_path(@course)) do |f| %>

  <div data-controller="payment" data-payment-token-value="<%= @token %>">
    <div data-payment-target="dropin"></div>
    <input type="hidden" name="nonce" data-payment-target="nonce" />
  </div>

  <div class="fields">
    <%= f.label :recipient %>
    <%= f.text_field :recipient %>
  </div>
  
  <div class="fields">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

<%= f.submit 'Create Order' %>
<% end %>

app/views/courses/edit.html.erb
<h1>編輯課程 <%= @course.name %></h1>

<%= render 'form', course: @course, btn_label: '編輯課程' %>

app/views/courses/index.html.erb
<h1>課程列表</h1>

<%= link_to "新增課程", new_course_path %>

<section class="course">
<% @courses.each do |course| %>
  <div class="card">
    (Rating:<%= course.reviews.size %>)
    <header>
      <%= course.name %></header>
      (Lecturer:<%= course.user&.username %>)
    <article>
      <%= course.intro %>
      <p>課程時數：<%= course.hour %></p>
    </article>
    <%= link_to "詳細內容", course_path(course) %>
    <%= link_to "編輯", edit_course_path(course) %>
    <%= link_to "刪除", course_path(course), method: 'delete', data: { confirm: '確認刪除？' } %>
  </div>
<% end %>
</section>

app/views/courses/new.html.erb
<h1>新增課程</h1>
<%= link_to "回到課程列表", courses_path %>
<%= render 'form', course: @course, btn_label: '新增課程' %>

app/views/courses/show.html.erb
<h1 data-controller="fav"
    data-fav-liked-value="<% user_signed_in? && current_user.favorite_courses.include?(@course) %>"
    data-fav-course-id-value="<%= @course.id %>"
>
  <%= @course.name %>
    <button data-fav-target="btn" 
            data-action="fav#like"
            >Like!
    </button> 
</h1>

<%= link_to '購買課程', buy_course_path(@course) %>

<%= link_to '返回課程列表', courses_path %>

<%= form_for(@review, url: course_reviews_path(@course), remote: true) do |form| %>

<div class="fields">
  <%= form.label :rating %>
  <%= form.select :rating, [1, 2, 3, 4, 5], include_blank: true %>
</div>

<div class="fields">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="fields">
  <%= form.label :content %>
  <%= form.text_area :content %>
</div>

<%= form.submit '送出' %>
<% end %>

<h2>評論</h2>
<div class="review-container">
  <%= render @reviews %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaZhuu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash_message' if notice %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>關於我們</h1>

app/views/pages/index.html.erb
<h1>123</h1>
<% if user_signed_in? %>
  已登入 <a href="/sign_out">登出</a>
<% else %>
  未登入 <a href="/sign_in">登入</a>
<% end %>

app/views/reviews/_review.html.erb
<section class="review">
    星數：<%= "☻" * review.rating %><%= "☺" * (5 - review.rating) %>
    <header><%= review.title %></header>
    <article>
      <%= review.content %>
    </article>
</section>

app/views/reviews/create.js.erb
var reviewContainer = document.querySelector('.review-container')

var el = document.createElement('div')
var reviewContent = `<%= render "review", review: @review %>`
el.innerHTML = reviewContent

reviewContainer.insertAdjacentElement("afterbegin", el.firstChild)

document.querySelector('#new_review').reset()

app/views/shared/_flash_message.html.erb
<%= notice %>

app/views/shared/_footer.html.erb
<footer>
&copy 2021 版權沒有
</footer>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <%= current_user.email %>
  <%= link_to "登出", sign_out_path, method: 'delete' %>
<% else %>
  <%= link_to "註冊", sign_up_path %>
  <%= link_to "登入", sign_in_path %>
<% end %>

app/views/users/sign_in.html.erb
<h1>會員登入</h1>

<%= form_for(@user, url: '/sign_in/check') do |form| %>
  <div class="fields">
    <%= form.label :email, '信箱' %>
    <%= form.email_field :email  %>
  </div>

  <div class="fields">
    <%= form.label :password, '密碼' %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit '登入' %>
  </div>
<% end %>

app/views/users/sign_up.html.erb
<h1>會員註冊</h1>

<%= form_for(@user, url: '/account_verify') do |form| %>
  <div class="fields">
    <%= form.label :email, '信箱' %>
    <%= form.email_field :email  %>
  </div>

  <div class="fields">
    <%= form.label :username, '姓名' %>
    <%= form.text_field :username %>
  </div>

  <div class="fields">
    <%= form.label :password, '密碼' %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit '註冊' %>
  </div>
<% end %>